name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    failOnThreshold: high  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-demographics-env-var
    pr_params:
      container.useEvents: $(pr_useEvents)
      container.processingActive: $(pr_processingActive)
      container.demographicsClientId: $(pr_demographicsClientId)
      container.demographicsTenantId: $(pr_demographicsTenantId)
    snd2_params:
      container.useEvents: $(snd2_useEvents)
      container.processingActive: $(snd2_processingActive)
      container.demographicsClientId: $(snd2_demographicsClientId)
      container.demographicsTenantId: $(snd2_demographicsTenantId)
    dev_params:
      container.useEvents: $(dev_useEvents)
      container.processingActive: $(dev_processingActive)
      container.demographicsClientId: $(dev_demographicsClientId)
      container.demographicsTenantId: $(dev_demographicsTenantId)
    test_params:
      container.useEvents: $(test_useEvents)
      container.processingActive: $(test_processingActive)
      container.demographicsClientId: $(test_demographicsClientId)
      container.demographicsTenantId: $(test_demographicsTenantId)
    pre_params:
      container.useEvents: $(pre_useEvents)
      container.processingActive: $(pre_processingActive)
      container.demographicsClientId: $(pre_demographicsClientId)
      container.demographicsTenantId: $(pre_demographicsTenantId)
    prd_params:
      container.useEvents: $(prd_useEvents)
      container.processingActive: $(prd_processingActive)
      container.demographicsClientId: $(prd_demographicsClientId)
      container.demographicsTenantId: $(prd_demographicsTenantId)
