services:
  ffc-pay-demographics:
    build:
      context: .
      target: production
    image: ffc-pay-demographics
    container_name: ffc-pay-demographics
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-demographics-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      DEMOGRAPHICS_TOPIC_ADDRESS: ${DEMOGRAPHICS_TOPIC_ADDRESS:-ffc-pay-demographics}${MESSAGE_QUEUE_SUFFIX}
      CUSTOMER_TOPIC_ADDRESS: ${CUSTOMER_TOPIC_ADDRESS:-ffc-pay-customer}${MESSAGE_QUEUE_SUFFIX}
      DEMOGRAPHICS_STORAGE_CONNECTION_STRING: ${DEMOGRAPHICS_STORAGE_CONNECTION_STRING}
      DEMOGRAPHICS_STORAGE_SHARE_NAME: ${DEMOGRAPHICS_STORAGE_SHARE_NAME:-demographics}
      DEMOGRAPHICS_STORAGE_FOLDER_NAME: ${DEMOGRAPHICS_STORAGE_FOLDER_NAME:-outbound}
      DAX_STORAGE_CONNECTION_STRING: ${DAX_STORAGE_CONNECTION_STRING}
      DAX_STORAGE_SHARE_NAME: ${DAX_STORAGE_SHARE_NAME:-demographics}
      DAX_STORAGE_FOLDER_NAME: ${DAX_STORAGE_FOLDER_NAME:-dax}
      POLLING_INTERVAL: ${POLLING_INTERVAL:-10000}
