services:
  ffc-pay-demographics:
    build:
      context: .
      target: production
    image: ffc-pay-demographics
    container_name: ffc-pay-demographics
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-demographics-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
