# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-pay-demographics:
    build:
      target: development
    depends_on:
    - ffc-pay-demographics-azurite
    image: ffc-pay-demographics-development
    container_name: ffc-pay-demographics-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-demographics-azurite:10000/devstoreaccount1;
      DEMOGRAPHICS_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-demographics-azurite:10000/devstoreaccount1;
      UPDATES_MESSAGE_QUEUE_HOST: MockHost
      UPDATES_MESSAGE_QUEUE_PASSWORD: MockPassword
      UPDATES_MESSAGE_QUEUE_USER: MockUser

  ffc-pay-demographics-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-pay-demographics-azurite:
    labels:
      com.docker.compose.pay.role: test

volumes:
  postgres_data: {}
