{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-demographics.config-map") -}}
{{- define "ffc-pay-demographics.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  ENABLED: {{ quote .Values.container.enabled }}
  DAX_ENABLED: {{ quote .Values.container.daxEnabled }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  DEMOGRAPHICS_STORAGE_CONNECTION_STRING: {{ quote .Values.container.demographicsStorageConnectionString }}
  DEMOGRAPHICS_STORAGE_SHARE_NAME: {{ quote .Values.container.demographicsStorageShareName }}
  DAX_STORAGE_CONNECTION_STRING: {{ quote .Values.container.daxStorageConnectionString }}
  DAX_STORAGE_SHARE_NAME: {{ quote .Values.container.daxStorageShareName }}
  DAX_STORAGE_FOLDER_NAME: {{ quote .Values.container.daxStorageFolder }}
  DAX_STORAGE_OUTBOUND_FOLDER_NAME: {{ quote .Values.container.daxStorageOutboundFolder }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  CUSTOMER_TOPIC_ADDRESS: {{ .Values.container.customerTopicAddress }}-{{ .Values.environmentCode }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  CUSTOMER_TOPIC_ADDRESS: {{ quote .Values.container.customerTopicAddress }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}
  {{- end }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  USE_EVENTS: {{ quote .Values.container.useEvents }}
{{- end -}}
