{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-demographics.container-secret") -}}
{{- define "ffc-pay-demographics.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  DEMOGRAPHICS_CLIENT_ID: {{ quote .Values.container.demographicsClientId }}
  DEMOGRAPHICS_CLIENT_SECRET: {{ quote .Values.container.demographicsClientSecret }}
  DEMOGRAPHICS_TENANT_ID: {{ quote .Values.container.demographicsTenantId }}
  UPDATES_MESSAGE_QUEUE_CONNECTION_STRING: {{ quote .Values.container.updatesMessageConnectionString }}
{{- end -}}
