environment: production
environmentCode:
name: ffc-pay-demographics
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-demographics

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-demographics-config-map

containerSecret:
  name: ffc-pay-demographics-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3003
  enabled: true
  daxEnabled: false
  azureStorageAccountName: ffcpay
  demographicsStorageConnectionString: myconnectionstring
  demographicsStorageShareName: demographics
  daxStorageConnectionString: myconnectionstring
  daxStorageShareName: demographics
  daxStorageFolder: dax
  daxStorageOutboundFolder: outbound
  messageQueueHost: namespace.servicebus.windows.net
  customerTopicAddress: ffc-pay-customer
  azureStorageUseConnectionString: false
  eventsTopicAddress: ffc-pay-events
  useEvents: true

postgresService:
  postgresDb: ffc_pay_demographics
  postgresqlHost: ffc-pay-demographics-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
