environment: production
environmentCode:
name: ffc-pay-demographics
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-demographics

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-demographics-config-map

containerSecret:
  name: ffc-pay-demographics-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  demographicsStorageConnectionString: myconnectionstring
  demographicsStorageShareName: demographics
  demographicsStorageFolder: outbound
  messageQueueHost: namespace.servicebus.windows.net
  demographicsTopicAddress: ffc-pay-demographics
  customerTopicAddress: ffc-pay-customer

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
